### ISSUE TITLE
Failed to activate the python-jedi package

### ISSUE THREAD

**Issue by rawjam** [saravanan-k90/python-jedi#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [python-jedi](https://github.com/saravanan-k90/python-jedi) package, v0.1.3

### Stack Trace

Failed to activate the python-jedi package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:355:117)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:334:19
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:640:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:804:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:617:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:231:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:409:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:162:14)
  at resetJedi (/Users/benjamindell/.atom/packages/python-jedi/lib/jedi-python3-provider.coffee:11:17)
  at /Users/benjamindell/.atom/packages/python-jedi/lib/jedi-python3-provider.coffee:99:3
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:133:21)
  at Object.<anonymous> (/Users/benjamindell/.atom/packages/python-jedi/lib/jedi-python3-provider.coffee:97:13)
  at Object.<anonymous> (/Users/benjamindell/.atom/packages/python-jedi/lib/jedi-python3-provider.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/benjamindell/.atom/packages/python-jedi/lib/jedi-python3-autocomplete.coffee:3:16)
  at Object.<anonymous> (/Users/benjamindell/.atom/packages/python-jedi/lib/jedi-python3-autocomplete.coffee:2:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:20.1 settings-view:open (atom-text-editor.editor)
     -0:14.3 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "neutron-ui",
      "neutron-syntax"
    ]
  },
  "python-jedi": {
    "Pathtopython": "python3"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.23.1
atom-django, v0.2.1
auto-update-packages, v0.2.2
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.7.0
django-templates, v0.4.0
file-icons, v1.5.2
jshint, v1.3.0
less-autocompile, v1.0.0
linter-htmlhint, v0.0.10
linter-less, v0.3.1
linter-python-pep8, v0.2.0
neutron-syntax, v0.6.2
neutron-ui, v0.3.0
project-manager, v1.15.5
python-jedi, v0.1.3

# Dev
No dev packages
```

**Comment by saravanan-k90** [comment]
The package seems to work fine even after this issue. But still it has to be fixed and I am trying to fix it.

**Comment by saravanan-k90** [comment]
@rawjam no issues when installed via 'apm install python-jedi'

**Comment by saravanan-k90** [comment]
I received the same error when installed the package with atom old version. After upgrading atom to new version., 'Failed to activate the python-jedi package' doesn't occur  anymore. So please check. Update atom to new release.
