### ISSUE TITLE
Uncaught Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by davides93** [saravanan-k90/python-jedi#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [python-jedi](https://github.com/saravanan-k90/python-jedi) package, v0.3.7

### Stack Trace

Uncaught Error: spawn ENAMETOOLONG

```
At C:\Users\Davide\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:262

Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:374:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (C:\Users\Davide\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:190:44)
    at new BufferedProcess (C:\Users\Davide\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:50:14)
    at file:///C:/Users/Davide/.atom/packages/python-jedi/lib/jedi-python3-provider.coffee:119:34
    at JediProvider.module.exports.JediProvider.requestHandler (file:///C:/Users/Davide/.atom/packages/python-jedi/lib/jedi-python3-provider.coffee:55:16)
    at C:\Users\Davide\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\Davide\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (C:\Users\Davide\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\Davide\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:276:19)
    at C:\Users\Davide\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61
```

### Commands

```
     -4:45.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:12.8.0 core:delete (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "python-tools"
    ]
  },
  "python-jedi": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-awk, v0.1.2
autocomplete-python, v1.8.1
language-latex, v0.6.1
latex-autocomplete, v0.5.3
latexer, v0.3.0
latextools, v0.8.1
pdf-view, v0.50.0
python-debugger, v0.1.0
python-indent, v0.4.3
python-jedi, v0.3.7
remote-sync, v4.1.2

# Dev
No dev packages
```

**Comment by saravanan-k90** [comment]
> Uncaught Error: spawn ENAMETOOLONG
> System: Unknown Windows Version

I do not know whether it works in windows os environment. 

Also you are using autocomplete-python. Please use either autocomplete-python or python-jedi => both are auto-complete. I think autocomplete-python may support windows environment well.

But still If you can solve this issue under windows environment., please solve it and send me a pull request., i will check it with linux os environment and release a new patch.
