### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by kenju254** [saravanan-k90/python-jedi#11]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Mac OS X 10.11.6
**Thrown From**: [python-jedi](https://github.com/saravanan-k90/python-jedi) package, v0.3.7

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom 2.app/Contents/Resources/app.asar/src/buffered-process.js:262

Error: spawn EACCES
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:379:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom 2.app/Contents/Resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/Applications/Atom 2.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/kennethkinyanjui/.atom/packages/python-jedi/lib/jedi-python3-provider.coffee:119:34
    at JediProvider.module.exports.JediProvider.requestHandler (/Users/kennethkinyanjui/.atom/packages/python-jedi/lib/jedi-python3-provider.coffee:55:16)
    at /Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
  2x -2:26.3.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  2x -2:25 core:backspace (atom-text-editor.editor.power-mode.is-focused)
  2x -2:23.9.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  9x -1:36.5.0 core:backspace (atom-text-editor#python-jedi.Pathtopython.editor.mini.is-focused)
     -0:48.9.0 core:select-all (atom-text-editor#python-jedi.Pathtopython.editor.mini.is-focused)
     -0:48.7.0 editor:delete-to-beginning-of-line (atom-text-editor#python-jedi.Pathtopython.editor.mini.is-focused)
     -0:47.2.0 core:select-all (atom-text-editor#python-jedi.Pathtopython.editor.mini.is-focused)
     -0:46.9.0 core:backspace (atom-text-editor#python-jedi.Pathtopython.editor.mini.is-focused)
     -0:46.1.0 core:paste (atom-text-editor#python-jedi.Pathtopython.editor.mini.is-focused)
 11x -0:32.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-flake8"
    ]
  },
  "python-jedi": {
    "Pathtopython": "/Users/kennethkinyanjui/.virtualenvs/flaskenv"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.4 (active)
atom-django, v0.3.2 (active)
atomic-emacs, v0.9.2 (active)
autocomplete-python, v1.8.6 (active)
git-plus, v5.16.2 (inactive)
linter, v1.11.16 (active)
linter-flake8, v1.13.2 (inactive)
minimap, v4.24.7 (active)
python-indent, v0.4.3 (active)
python-jedi, v0.3.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by saravanan-k90** [comment]
Do not use autocomplete-python along with python-jedi => both are autocomplete. try deactivating autocomplete-python and check with proper python path.

```
"python-jedi": {
    "Pathtopython": "/Users/kennethkinyanjui/.virtualenvs/flaskenv"
  }
```
pathtopython should point to python executable.. may be like this => /home/user/virtualenv/bin/python

**Comment by saravanan-k90** [comment]
did you try?
