### ISSUE TITLE
Uncaught Error: spawn E2BIG

### ISSUE THREAD

**Issue by rogerbinns** [saravanan-k90/python-jedi#12]
I have no idea how to reproduce this, but there error dialog keeps appearing.  Just doing regular editing,

**Atom Version**: 1.9.9
**System**: Ubuntu 16.04.1
**Thrown From**: [python-jedi](https://github.com/saravanan-k90/python-jedi) package, v0.3.7

### Stack Trace

Uncaught Error: spawn E2BIG

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:262

Error: spawn E2BIG
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:379:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at /home/rogerb/Dropbox/dot-atom/packages/python-jedi/lib/jedi-python3-provider.coffee:119:34
    at JediProvider.module.exports.JediProvider.requestHandler (/home/rogerb/Dropbox/dot-atom/packages/python-jedi/lib/jedi-python3-provider.coffee:55:16)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:02.8.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:02.3.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-clang"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/space",
    "themes": [
      "one-dark-ui",
      "slime"
    ]
  },
  "python-jedi": {
    "enablePython2": true
  }
}
```

### Installed Packages

```coffee
# User
aligner-python, v1.0.1 (active)
atom-beautify, v0.29.10 (active)
atom-jinja2, v0.5.0 (active)
autocomplete-clang, v0.9.4 (active)
autocomplete-java, v1.2.5 (inactive)
autocomplete-python, v1.8.6 (active)
bug-report, v0.7.1 (active)
clang-format, v1.25.0 (active)
expose, v0.12.1 (inactive)
hyperclick, v0.0.37 (active)
language-csv, v1.1.2 (active)
language-diff, v0.4.0 (active)
language-javascript-semantic, v0.2.1 (active)
language-restructuredtext, v1.0.0 (active)
linter, v1.11.16 (active)
linter-clang, v3.4.4 (inactive)
linter-csslint, v1.3.2 (active)
linter-eslint, v7.2.4 (active)
linter-flake8, v1.13.2 (active)
linter-javac, v1.9.4 (active)
linter-json-lint, v0.1.1 (active)
linter-rst, v0.0.3 (active)
merge-conflicts, v1.4.4 (active)
pigments, v0.32.1 (active)
python-jedi, v0.3.7 (active)
python-tools, v0.6.8 (active)
quick-editor, v0.4.3 (inactive)
slime, v1.6.1 (active)
symbols-tree-view, v0.13.2 (active)
tablr, v1.4.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by saravanan-k90** [comment]
This is what i found. E2BIG (ERROR_META_EXPANSION_TOO_LONG) means that the argument list is too long.
Argument list sent to buffered process may be too long.

I cannot be able to reproduce this error in my system to solve it.

**Comment by rogerbinns** [comment]
There may be one possibility.  Are file contents sent as command line params?  [This file](https://github.com/rogerbinns/apsw/blob/master/tests.py) is part of my source and is 325kb.

**Comment by saravanan-k90** [comment]
yes file contents are sent as command line params. I get the same error when i tried test.py. Can you give any suggestions.

**Comment by rogerbinns** [comment]
In general sending file contents as command line parameters is frowned upon, and often doesn't work anyway.  Command lines are visible to every other process on the system, so they leak information.  And every operating system has limits on how long the command lines can be.  For example it can be as short as 128 bytes, or as long as a megabyte.

The preferred alternative is to feed the file contents as standard input to the process.  That doesn't leak any information, doesn't hit limits, and tends to work well.  Some processes can't handle that and require actual files (and file names).  In that case you'd need to use temporary files that are deleted after the process completes.

**Comment by saravanan-k90** [comment]
I have fixed this issue. Please check.

**Comment by rogerbinns** [comment]
I can confirm that my ~300kb python file now opens and works just fine.  Closing.
