### ISSUE TITLE
Uncaught SyntaxError: Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by whimshot** [saravanan-k90/python-jedi#14]
I didn't do nothin' I was just typing and it went off.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [python-jedi](https://github.com/saravanan-k90/python-jedi) package 0.3.8

### Stack Trace

Uncaught SyntaxError: Unexpected token P in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html:1

SyntaxError: Unexpected token P in JSON at position 0
    at Object.parse (native)
    at stdout (/packages/python-jedi/lib/jedi-python3-provider.coffee:96:34)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
 21x -2:50.1.0 core:backspace (input.hidden-input)
     -2:34.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -2:34.4.0 refactor:done (input.hidden-input)
     -2:34.4.0 editor:newline (input.hidden-input)
     -2:02.0 core:copy (input.hidden-input)
     -1:49.5.0 core:paste (input.hidden-input)
 43x -1:47.1.0 core:move-left (input.hidden-input)
  4x -1:42.7.0 core:move-right (input.hidden-input)
     -1:40.8.0 core:backspace (input.hidden-input)
     -1:39.3.0 core:save (input.hidden-input)
 15x -1:31 core:undo (input.hidden-input)
     -1:11.8.0 core:backspace (input.hidden-input)
  2x -1:02.4.0 core:save (ul.list-inline.tab-bar.inset-panel)
     -0:22.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:22.8.0 refactor:done (input.hidden-input)
     -0:22.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-clock 0.1.13 
atom-python-run 0.7.3 
atom-python-virtualenv 0.14.0 
atom-runner 2.7.1 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
file-icons 2.1.9 
git-blame 1.1.1 
git-control 0.9.0 
git-plus 7.9.3 
Hydrogen 1.19.0 
intentions 1.1.5 
language-kivy 0.1.1 
language-markdown 0.25.1 
language-systemd 0.1.1 
language-terraform 0.8.1 
linter 2.2.0 
linter-markdown 5.1.0 
linter-pycodestyle 2.0.2 
linter-pylama 0.9.3 
linter-pylint 2.1.0 
linter-python 3.1.2 
linter-python-pep8 0.2.0 
linter-ui-default 1.6.3 
markdown-preview-plus 2.4.10 
markdown-toc 0.4.2 
markdown-writer 2.6.5 
minimap 4.29.3 
project-manager 3.3.5 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.1.0 
python-isort 0.0.7 
python-jedi 0.3.8 
python-tools 0.6.9 
refactor 0.11.5 
script 3.15.0 
symbol-gen 1.3.1 
symbols-tree-view 0.14.0 
tail 0.1.0 
tidy-markdown 3.0.1 
```

**Comment by saravanan-k90** [comment]
i am extremely sorry @whimshot  my position is bad now(only intern job, less money, less internet, old linux system)... so i may not be able to try to check or solve the issue you have opened. But i really appreciate for opening issue in the plugin.

**Comment by whimshot** [comment]
@saravanan-k90 Understood.
