### ISSUE TITLE
autocomplete-python not working in atom

### ISSUE THREAD

**Issue by MacPacman** [saravanan-k90/python-jedi#17]
Looks like this error originated from Jedi. Please do not report such issues in autocomplete-python issue tracker. Report them directly to Jedi. Turn off outputProviderErrors setting to hide such errors in future. Traceback output:
Traceback (most recent call last):
  File "C:\Users\Xarvis_7\.atom\packages\autocomplete-python\lib/completion.py", line 374, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Xarvis_7\.atom\packages\autocomplete-python\lib/completion.py", line 363, in _process_request
    request.get('prefix', '')))
  File "C:\Users\Xarvis_7\.atom\packages\autocomplete-python\lib/completion.py", line 115, in _serialize_completions
    for signature, name, value in self._get_call_signatures(script):
  File "C:\Users\Xarvis_7\.atom\packages\autocomplete-python\lib/completion.py", line 80, in _get_call_signatures
    call_signatures = script.call_signatures()
  File "C:\Users\Xarvis_7\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 297, in call_signatures
    helpers.get_call_signature_details(self._get_module(), self._pos)
  File "C:\Users\Xarvis_7\.atom\packages\autocomplete-python\lib\jedi\api\helpers.py", line 290, in get_call_signature_details
    node.children[0], *_get_index_and_key(node.children, position))
  File "C:\Users\Xarvis_7\.atom\packages\autocomplete-python\lib\jedi\api\helpers.py", line 236, in _get_index_and_key
    if nodes_before[-1].type == 'arglist':
IndexError: list index out of range

**Comment by saravanan-k90** [comment]
Just uninstall plugin named "python-jedi" from atom. May be you would have installed both [autocomplete-jedi](https://atom.io/packages/autocomplete-python) =>_recommended_ and [python-jedi](https://atom.io/packages/python-jedi) => I am not maintaining it for multiple reasons.
Please try to go through the issues raised by bots or spam or human for **python-jedi** and the reply i had given.

As you know the solutions, please try to solve it internally. To your notice, i do not have a well equipped computer to even run a test through any plugins.

**_Never Mind:_** Can you buy me a computer, all you can do is just raise some issues and play dummy hats with my reply internally(brain-mind voice) and externally(https://en.wikipedia.org/wiki/Speech). 
**_Truth:_** They see what i see. They hear what i speak. They hear what i speak inside my mind. I never granted anything even though "i am all and i am nothing".
